### ISSUE TITLE
error: Internal GD font () not available. Use only 1-5.

### ISSUE THREAD

**Issue by 924517905** [mewebstudio/captcha#109]
system:centos7 and ubuntu16
laravel5.5
error:
 Intervention \ Image \ Exception \ NotSupportedException
Internal GD font () not available. Use only 1-5.

1 dont how to solve it

**Comment by 13804907420** [comment]
+1

**Comment by 13804907420** [comment]
在配置文件里指定字体就好了

> 'default'   => [
        'length'    => 5,
        'width'     => 120,
        'height'    => 36,
        'quality'   => 90,
        'fonts'     =>['..\vendor\mews\captcha\assets\fonts\Asap_700.ttf'],
    ],

**Comment by 924517905** [comment]
按照操作了，还是报错，我直接改intervention\image\gd\font.php里的代码，$internal font =5,强制了,不过字体还是小啊

**Comment by 13804907420** [comment]
我改代码字体也小，好像没用上字体，后来我改的配置就好了，字体也大了。

[captcha.zip](https://github.com/mewebstudio/captcha/files/1272802/captcha.zip)
把fonts换成绝对的字体路径数组试试，比如 C:\1.ttf

**Comment by 924517905** [comment]
绝对路径不出错了，灰常感谢
