### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by ghost** [mewebstudio/captcha#12]
I get this error:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException
Call to undefined method Mews\Captcha\Facades\Captcha::img()
```

And I followed your steps to config, set alias and set providers

thaks

**Comment by toplan** [comment]
my fork: https://github.com/toplan/captcha
use rewrite method (  Captcha::img() ) return a image data base on 64!
then just enjoy it:
<img src="{{Captcha::img()}}">
