### ISSUE TITLE
Captcha always return "validation.captcha" even the answer is correct.

### ISSUE THREAD

**Issue by tenshiangel** [mewebstudio/captcha#129]
> I always receive a "validation.captcha" error from the validation. I spent 2 days in working in this problem. Here is my Controller:

> `$validator = Validator::make($request->all(), [`
               ` 'first_name' => 'required',`
                `'last_name' => 'required',`
                `'captcha' => 'required|captcha',`
           ` ]);`
            `if ($validator->passes()) {`
                `$user = new User;`
                `$user->first_name = $request->first_name;`
                `$user->last_name = $request->last_name;`

                `return response()->json(['success'=>'Another User has been added..', 'image' => captcha_img('flat')]);`
            
`}`
            `else {`
                `return response()->json(['error' => json_encode($validator->errors()) ,'image' => captcha_img('flat')]);`
            `}`
  return response()->json(['success'=>'Another User has been added..', 'image' => captcha_img('flat')]);
            
}
            else {
                return response()->json(['error' => json_encode($validator->errors()) ,'image' => captcha_img('flat')]);
            }

> I also add the following answers I've found in other issues. In `Kernel.php`
`\Illuminate\Session\Middleware\StartSession::class,`

> In `CaptchaServiceProvider.php` on line 29
`$this->app['router']->get('captcha/{config?}', '\Mews\Captcha\CaptchaController@getCaptcha')->middleware('web');`

> Even I applied the codes above, still the captcha validation always return a `validation.captcha`. Unless if I remove the `'captcha' => 'required|captcha'` from the validation. I really need help regarding on this.

**Comment by tenshiangel** [comment]
I really don't understand what is the further meaning of "validation.captcha". I hope someone can clearly specify the meaning of that error.

**Comment by sepehr09** [comment]
i have same problem. any idea?

**Comment by mr-mr7** [comment]
i have same problem +1
