### ISSUE TITLE
In Laravel 5.5, validation always fail even if correct captcha is input

### ISSUE THREAD

**Issue by RockWithBoA** [mewebstudio/captcha#136]
Below is my test code. It always return Incorrect. I'm a newbie in Laravel, so could anyone help fix this issue?

- Router

`Route::post('/contact', 'RequirementFormController@submit');`

- Controller
```
<?php

namespace App\Http\Controllers;

use Validator;
use Illuminate\Http\Request;

class RequirementFormController extends Controller
{
    public function submit(Request $request) {
        $rules = ['captcha' => 'required|captcha'];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails())
        {
            echo '<p style="color: #ff0000;">Incorrect!</p>';
        }
        else
        {
            echo '<p style="color: #00ff30;">Matched :)</p>';
        }
    }
}
```

**Comment by RockWithBoA** [comment]
After debugging, found the default is case-sensitive. Issue resolved after changing to case-insensitive.

**Comment by Thicola** [comment]
How did you change to case-insensitive? i saw there are lots of similar problem and no documentation is released on this. 
please share.. thanks
