### ISSUE TITLE
How to change error message?

### ISSUE THREAD

**Issue by shinokada** [mewebstudio/captcha#138]
I get  `validation.captcha` when I submit with a wrong letter. How can I change this message?

**Comment by ZhangChinfu** [comment]
Hello, You need Open Session.
<img width="335" alt="default" src="https://user-images.githubusercontent.com/12717486/40574569-f79f5c1a-6106-11e8-9b5b-1e2cf71c6256.PNG">

**Comment by ZhangChinfu** [comment]
Add Text in  \resources\lang\en\validation.php
```
'captcha' => 'The :attribute is error.',

'attributes' => [
	'captcha' => 'Captcha',
]
```

**Comment by shinokada** [comment]
Thanks. Fixed.
