### ISSUE TITLE
error_reporting | ob_clean(): failed to delete buffer. No buffer to delete

### ISSUE THREAD

**Issue by MohandesaliRahnema** [mewebstudio/captcha#144]
error_reporting | ob_clean(): failed to delete buffer. No buffer to delete
-- | --
line | 23
file |/vendor/mews/captcha/src/CaptchaController.php

to fix it please use 
if (ob_get_contents())
        {
            ob_clean();
        }

**Comment by csmtcy** [comment]
I think should create a pull request for this update.

**Comment by mewebstudio** [comment]
56b044e
