### ISSUE TITLE
Captcha image loaing failed!

### ISSUE THREAD

**Issue by mkzaker** [mewebstudio/captcha#17]
hi dear,
after publish laravel site to cpane captcha image loading failed!
what's the problem?

**Comment by osfed** [comment]
Remove the following lines in Captcha.php, It works for me

ob_start();
$content = ob_get_clean();

return Response::make($content, 200)
            ->header('cache-control', 'no-cache, no-store, max-age=0, must-revalidate')
            ->header('pragma', 'no-cache')
            ->header('content-type', 'image/jpeg')
            ->header('content-disposition', 'inline; filename=captcha.jpg');

**Comment by toplan** [comment]
i am rewrite img() and create() method,my fork: https://github.com/toplan/captcha
use the rewrite method ( Captcha::img() ) return a image data base on 64!
enjoy it:
```html
<img src=" {{ Captcha::img() }} ">
````

**Comment by dolia** [comment]
I got the save problem too ! How to solve????????
