### ISSUE TITLE
Call to undefined function Intervention\Image\Gd\imagettfbbox()

### ISSUE THREAD

**Issue by itsowaisnoor** [mewebstudio/captcha#190]
I am facing this error while trying to display captcha_img(). My current Laravel version is 5.8.
Please Help!

**Comment by nimaamiri92** [comment]
+1

**Comment by esmaily** [comment]
i have same error

**Comment by itsowaisnoor** [comment]
> i have same error

Hello there.
I was able to fix this issue because I changed PHP version from PHP 7.1 to 7.2*. Please try that...
