### ISSUE TITLE
Cannot see characters properly - padding around text required

### ISSUE THREAD

**Issue by bachras** [mewebstudio/captcha#217]
Hi,

Thanks for plugin. 

I am struggling to display captcha image with fully visible characters. Please see the image below: 
<img width="290" alt="Screenshot 2021-02-02 at 12 38 45" src="https://user-images.githubusercontent.com/13886417/106601787-f5797200-6553-11eb-8148-21542beaac5d.png">

As you can see both 'gg' letters gets cut, so captcha images has text pushed to the right. I edited Captcha.php file in vendor folder and set marginTop = 0 in the following function 

````
    protected function text(): void
    {
        //$marginTop = $this->image->height() / $this->length;
        $marginTop = 0;

        $text = $this->text;
        if (is_string($text)) {
            $text = str_split($text);
        }

        foreach ($text as $key => $char) {
            $marginLeft = $this->textLeftPadding + ($key * ($this->image->width() - $this->textLeftPadding) / $this->length);

            $this->image->text($char, $marginLeft, $marginTop, function ($font) {
                /* @var Font $font */
                $font->file($this->font());
                $font->size($this->fontSize());
                $font->color($this->fontColor());
                $font->align('left');
                $font->align('top');
                $font->angle($this->angle());
            });
        }
    }
````
I think textLeftPadding and marginTop values are incorrect and padding around characters could be increased from all sides.

Captcha config:

````
    'default' => [
        'length' => 6,
        'width' => 216,
        'height' => 72,
        'quality' => 90,
        'math' => false,
        'expire' => 60,
        'encrypt' => false,
    ],
````
Thanks

**Comment by LiXunGuan** [comment]
I found that this problem is caused by imagick.
Please modify the `driver` in config/image.php
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Image Driver
    |--------------------------------------------------------------------------
    |
    | Intervention Image supports "GD Library" and "Imagick" to process images
    | internally. You may choose one of them according to your PHP
    | configuration. By default PHP's "GD Library" implementation is used.
    |
    | Supported: "gd", "imagick"
    |
    */

    'driver' => 'gd'

];

```

**Comment by fullstackprofile** [comment]
Hi , i'm not currently using `imagick ` , but have the same issue , any suggestions ?

**Comment by LiXunGuan** [comment]
> Hi , i'm not currently using `imagick ` , but have the same issue , any suggestions ?

You can use the elimination method to locate the problem location.

**Comment by bachras** [comment]
@LiXunGuan I have mentioned where is the problem  in my question. Just setting marginTop = 0 fixes the issue.

**Comment by LiXunGuan** [comment]
> 

This issue has not been dealt with yet, can you raise a pr?

**Comment by LiXunGuan** [comment]
@bachras This issue has not been dealt with yet, can you raise a pr?
