### ISSUE TITLE
Captcha not working with Fortify Laravel 9

### ISSUE THREAD

**Issue by whlives** [mewebstudio/captcha#235]
Captcha not working with  Laravel 9，The composer.json reference version is earlier than that of laravel

**Comment by libiannyatakom** [comment]
I'm also having a similar problem
`composer require mews/captcha`

and get an error message like the following
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mews/captcha[3.2.0, ..., 3.2.4] require php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
    - mews/captcha[3.2.5, ..., 3.2.6] require illuminate/config ~5|^6|^7|^8 -> found illuminate/config[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires mews/captcha ^3.2 -> satisfiable by mews/captcha[3.2.0, ..., 3.2.6].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require mews/captcha:*" to figure out if any version is installable, or "composer require mews/captcha:^2.1" if you know which you need.`

**Comment by xndbogdan** [comment]
A PR has been made.
https://github.com/mewebstudio/captcha/pull/236

**Comment by xndbogdan** [comment]
If you're in an emergency and really need laravel 9 compatibilty you can add my fork in your composer.json, or make your own.
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/xndbogdan/captcha.git"
        }
    ],
