### ISSUE TITLE
404 Error!

### ISSUE THREAD

**Issue by javadzanguei** [mewebstudio/captcha#247]
I use Laravel 9.34 and livewire 2.10 and mews/captcha 3.2.9
My site worked correctly in local but in server I get 404 error for captcha image.

`return <<<'blade'
            <div>
                {!! captcha_img('flat') !!}
                <svg style="cursor: pointer;" wire:click="refreshCaptcha" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z"/>
                  <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z"/>
                </svg>
            </div>
        blade;`

**Comment by cikucu** [comment]
same here, how do u solve it?

**Comment by javadzanguei** [comment]
> same here, how do u solve it?

I'm so sorry @cikucu . I forgot how the problem was solved.
