### ISSUE TITLE
Can you please update it for Laravel 10

### ISSUE THREAD

**Issue by AlieSoomro** [mewebstudio/captcha#268]
I am using Laravel 10, but currently, I am unable to use mews/captcha. Can you please update it for Laravel 10.

**Comment by angelej** [comment]
Hi @AlieSoomro,
the version [v3.3.0](https://github.com/mewebstudio/captcha/releases/tag/3.3.0) seems to support laravel 10.
However, for some reason [v3.3.1](https://github.com/mewebstudio/captcha/releases/tag/3.3.1) dropped the support for laravel 9 & 10.

Was this on purpose @mewebstudio?

**Comment by mewebstudio** [comment]
No, I think there was a mistake. Sorry, I'll fix it.

**Comment by mewebstudio** [comment]
Fixed [https://github.com/mewebstudio/captcha/commit/7aee0e80bcf7eb17fc0d574244e384e56ae2af77](https://github.com/mewebstudio/captcha/commit/7aee0e80bcf7eb17fc0d574244e384e56ae2af77)
