### ISSUE TITLE
Captcha Check Problem When $formId Is Given

### ISSUE THREAD

**Issue by laimisf** [mewebstudio/captcha#28]
The mews captcha has a problem when $formId value is provided with img() function, like Captcha::img('registerForm'), because when Captcha validation is executed, this parameter ('registerForm') is not included in src/Mews/Captcha/CaptchaValidator.php and validation assumes that $formId value is empty, so it cannot find correct captcha session (which is captchaHash['registerForm']) and, of course, validation always fails.

**Comment by laimisf** [comment]
Also, when validation is executed, all 'captchaHash' session array is forgotten, instead of forgetting only one single array element on which check was executed.
Why not to do Session::forget('captchaHash.' . $formId) in check() function instead of forgetting all array elements, like now (Session::forget('captchaHash')?

One more thing, check() function could have $forgetSession parameter by default set to 'true', like check($value, $formId = null, $forgetSession = true). In this way, people could use this function for captcha check via AJAX and not forget the session that inner script validation could pass.

Edited function proposal:

```php
public function check($value, $formId = null, $forget = true)
    {
        if (!$formId) {
            $formId = hash('sha256', URL::previous());
        }
        $captchaHash = Session::get('captchaHash.' . $formId);
        $result = $value != null
            && $captchaHash != null
            && strlen($value) === $this->config['length'] // must be of the same length right?
            && $this->hashCheck($value, $captchaHash);
        // forget the hash to prevent replay
        if($forget) Session::forget('captchaHash');
        return $result;
    }
```

**Comment by toplan** [comment]
uhh...I think if couldn't pass via AJAX, should create a new captcha code and return the img data back to browser!

**Comment by toplan** [comment]
```php
if( ! $result || ! \Request::ajax() ){
            // forget the hash to prevent replay
            Session::forget('captchaHash');
 }
```
