### ISSUE TITLE
Captcha image not displaying

### ISSUE THREAD

**Issue by danboh** [mewebstudio/captcha#29]
Hello,

Just trying this for the first time and can't get it to work in my dev environment. The image is just not rendering. After the page loads, the source of the image is: http://localhost/site/public/captcha?454234

When going to the image URL the error the browser throws is: "The image cannot be displayed because it contains errors"

I'm working on a Windows dev environment, already checked to make sure the necessary dlls were installed. Also published my site to a staging Unix environment and still having the same results.

Is this a bug or something I'm missing?

**Comment by mauris** [comment]
Hi @danboh can you post your usage code here so that we can take a look?

**Comment by danboh** [comment]
Hello Mauris,

Thanks for wanting to help. I still haven't been able to figure it out.

I'm not exactly sure what you'd like to see, but here is how I call the captcha in my view:

<div class="form-group">
            <label for="captcha">{{{ Lang::get('confide::confide.captcha') }}}</label>
            <img src="{{ Captcha::img() }}">
            <input class="form-control" placeholder="{{{ Lang::get('confide::confide.captcha') }}}" type="text" name="captcha" id="captcha">
        </div>

**Comment by danboh** [comment]
I still haven't been able to figure this one out...

**Comment by followtheart** [comment]
@danboh Does you use this captcha  plugin?

**Comment by danboh** [comment]
@followtheart I'm trying to, but it doesn't work.

**Comment by followtheart** [comment]
[Demo](https://github.com/followtheart/Laravel-5-Starter/blob/master/app/Http/routes.php#L47)

**Comment by danboh** [comment]
@followtheart Laravel 4.2

**Comment by cmschandan** [comment]
![error22](https://user-images.githubusercontent.com/21227329/73119805-2318fc00-3f8d-11ea-8f64-59f1b7721b13.JPG)
please check this image. my image is not loading but refresh button is working

**Comment by alissonalberini** [comment]
I went through the problem, in a deploy on xamp with localhost configuration.
When opening the url in a new tab, the error was 500, so I ran to enable the debug to true, and see the return, which was the lack of extension "gd"
