### ISSUE TITLE
Undefined property: Intervention\Image\EncodedImage::$encoded

### ISSUE THREAD

**Issue by light8771** [mewebstudio/captcha#305]
- php ``8.1.13``
- laravel ``10.48.20``
- mews/captcha ``3.4.1``
- intervention/image ``3.7.2``

``domain/captcha/api`` Access error

![image](https://github.com/user-attachments/assets/9fcc25df-0a4e-40c2-8685-7c87e7bd7f85)

I need to change the error line to ``'img' => $this->image->encode()->toDataUri()`` to run normally

**Comment by ithsjeff** [comment]
I had no problem after fixing the Providers problem here #306 

If you still had a problem can you shared more detailed.

**Comment by ariadys** [comment]
same

**Comment by ithsjeff** [comment]
Okay, can you share more details so I can replicated and try fix it.

**Comment by aleiku-syscom** [comment]
PHP 8.3.10
Laravel 11.20.0
mews/captcha 3.4.2
intervention/image 3.8.0

Hi, due to the changes in version 3.8.0 of intervention/image, 
the new ability to read instances of EncodedImage::class with ImageManager::class has been introduced. 
However, the Intervention\Image\EncodedImage class no longer has the encode property.

```
<?php

declare(strict_types=1);

namespace Intervention\Image;

use Intervention\Image\Interfaces\EncodedImageInterface;

class EncodedImage extends File implements EncodedImageInterface
{
    /**
     * Create new instance
     *
     * @param string $data
     * @param string $mediaType
     */
    public function __construct(
        protected string $data,
        protected string $mediaType = 'application/octet-stream'
    ) {
    }

    /**
     * {@inheritdoc}
     *
     * @see EncodedImageInterface::mediaType()
     */
    public function mediaType(): string
    {
        return $this->mediaType;
    }

    /**
     * {@inheritdoc}
     *
     * @see EncodedImageInterface::mimetype()
     */
    public function mimetype(): string
    {
        return $this->mediaType();
    }

    /**
     * {@inheritdoc}
     *
     * @see EncodedImageInterface::toDataUri()
     */
    public function toDataUri(): string
    {
        return sprintf('data:%s;base64,%s', $this->mediaType, base64_encode($this->data));
    }
}
```

**Comment by light8771** [comment]
@ithsjeff  Hi, I updated to `3.4.2` and the problem is not solved

> PHP 8.3.10 Laravel 11.20.0 mews/captcha 3.4.2 intervention/image 3.8.0
> 
> Hi, due to the changes in version 3.8.0 of intervention/image, the new ability to read instances of EncodedImage::class with ImageManager::class has been introduced. However, the Intervention\Image\EncodedImage class no longer has the encode property.
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace Intervention\Image;
> 
> use Intervention\Image\Interfaces\EncodedImageInterface;
> 
> class EncodedImage extends File implements EncodedImageInterface
> {
>     /**
>      * Create new instance
>      *
>      * @param string $data
>      * @param string $mediaType
>      */
>     public function __construct(
>         protected string $data,
>         protected string $mediaType = 'application/octet-stream'
>     ) {
>     }
> 
>     /**
>      * {@inheritdoc}
>      *
>      * @see EncodedImageInterface::mediaType()
>      */
>     public function mediaType(): string
>     {
>         return $this->mediaType;
>     }
> 
>     /**
>      * {@inheritdoc}
>      *
>      * @see EncodedImageInterface::mimetype()
>      */
>     public function mimetype(): string
>     {
>         return $this->mediaType();
>     }
> 
>     /**
>      * {@inheritdoc}
>      *
>      * @see EncodedImageInterface::toDataUri()
>      */
>     public function toDataUri(): string
>     {
>         return sprintf('data:%s;base64,%s', $this->mediaType, base64_encode($this->data));
>     }
> }
> ```

**Comment by felixmertins** [comment]
we are facing same issue, after changing encoded to toDataURI() it works for us too.

**Comment by ithsjeff** [comment]
@light8771 @felixmertins Okay, Waiting to this PR #309 to be merged.
