### ISSUE TITLE
Laravel 11 |  Target class [validator] does not exist.

### ISSUE THREAD

**Issue by hani221b** [mewebstudio/captcha#316]
Issue message: **Target class [validator] does not exist.**

how to reproduce: 

1- Add the service provider to app.php config file:
```

    'providers' => [
        // ...
        Mews\Captcha\CaptchaServiceProvider::class,
    ]
```

After that whenever I try to run `php artisan optimize` or reach the captcha route I encounter the previous error message.

**Comment by Rettorio** [comment]
hey may i know what you do solve the issue ?
