### ISSUE TITLE
Method validateCaptcha does not exist.

### ISSUE THREAD

**Issue by wiyfn** [mewebstudio/captcha#34]
I have following issue: Method [validateCaptcha] does not exist.BadMethodCallException in Validator.php line 2615:

```use App\Models\Question;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use Mews\Captcha;
....
 protected $rules = array(
        'name'     => 'required',
        'captcha'  => 'required|captcha');
.....
 $validation = Validator::make($data, $this->rules);
......
```

**Comment by mewebstudio** [comment]
Update package
```composer update```
and
```composer dump-autoload```
try this way again.

**Comment by wiyfn** [comment]
It work ! Thank.

**Comment by closca** [comment]
I got same issue on L4, i made what you sugested but the error is still there,

**Comment by akanevsky** [comment]
I also got the same issue as the above posters. Please help.

**Comment by hoavq214** [comment]
Please help me.

**Comment by KeepChen** [comment]
I got same issue on L5.2,but when I tried to add code after line 25 in CaptchaServiceProvider to:
Validator::extend('captcha', function($attribute, $value, $parameters, $validator){
    return captcha_check($value);
});
It's works. @akanevsky @hoavq214
