### ISSUE TITLE
display error when i execute "php artisan route:cache"

### ISSUE THREAD

**Issue by zhangmazi** [mewebstudio/captcha#39]
errors information:
[LogicException]                                                             
  Unable to prepare route [captcha/{config?}] for serialization. Uses Closure

**Comment by zhangmazi** [comment]
@lbausch  I used route to Controller,but it display the same errors information.
#Controller Code
>    public function Captcha()
>    {
>        return Captcha::create();
>    }

**Comment by lbausch** [comment]
As far as I can see the package needs to route to a controller - but not you in your application. Also see the changes in the PR: https://github.com/mewebstudio/captcha/pull/42/files
Maybe @mewebstudio releases a new version including the changes soon.

**Comment by zhangmazi** [comment]
@lbausch thanks. I am trying...And composer update now..

**Comment by zhangmazi** [comment]
I had upgrade to 2.0.2,And Larave5.1.1，that is ok! thanks
