### ISSUE TITLE
ErrorException include Classloader

### ISSUE THREAD

**Issue by stijnos7** [mewebstudio/captcha#41]
Everything works fine on my localhost but when i'm uploading the stuff, this is my issue:

ErrorException in ClassLoader.php line 412:
include(/customers/b/f/a/smashpoint.be/httpd.www/webshop/vendor/intervention/image/src/Intervention/Image/ImageManager.php): failed to open stream: No such file or directory (View: /customers/b/f/a/smashpoint.be/httpd.www/webshop/resources/views/auth/register.blade.php)

Sombody who knows what the problem is?

**Comment by mewebstudio** [comment]
/customers/b/f/a/smashpoint.be/httpd.www/webshop/vendor/intervention/image/src/Intervention/Image/ImageManager.php giving permission to read the file and try again.
