### ISSUE TITLE
composer update fails,requires intervention/image ~2.2

### ISSUE THREAD

**Issue by HeChenTao** [mewebstudio/captcha#43]
When I try to run `composer update`,it shows `mews/captcha dev-master requires intervention/image ~2.2`.but I have installed intervention/image  high version,so how to solve this problem

**Comment by mewebstudio** [comment]
Before, the `intervention/image` and `mews/captcha` remove. Afterwards, reinstall `composer update` and `composer dump-autoload` then run a command.

With the last version I have works fine.

`Removing intervention/image (2.2.1)`
`Installing intervention/image (2.2.2)`
`Downloading: 100%`
