### ISSUE TITLE
imagettftext(): Could not read font

### ISSUE THREAD

**Issue by kvailas** [mewebstudio/captcha#45]
I got imagettftext(): Could not read font (on image action).
Ive tried to change the permissions on vendor public folder of mews/captcha but no luck.
The assets are there. but for some reason the imagettftext cannot read it?
Thanks in advance.

**Comment by mewebstudio** [comment]
Captcha package try installing again.

**Comment by Abdelrhman-Allam** [comment]
I checked up the code and I found this:
mews/captcha/src/Captcha.php
what you are doing reading fonts folder add assign it to array of fonts[]:
  $this->fonts = $this->files->files(__DIR__ . '/../assets/fonts');
Then code using the font by random the font in the array 
    protected function font()
    {
        return $this->fonts[rand(0, count($this->fonts) - 1)];
    }
So when add file not font file such a version control files like( sourcesafe, github, hidden file,..) the code will throw exception imagettftext(): 

I think it is good to check the extension of fonts .ttf before adding it to the fonts array

**Comment by YaoCancan** [comment]
<img width="348" alt="wx20170524-114643 2x" src="https://cloud.githubusercontent.com/assets/10437409/26387428/2b29253c-4080-11e7-93af-ab1e331c0f95.png">
![4186c15f-68c1-4ec4-a96e-747f182f9dbb](https://cloud.githubusercontent.com/assets/10437409/26387430/2dfc5720-4080-11e7-8a3e-9299e4565e0d.png)
Look at the quality of these fonts, you should understand
