### ISSUE TITLE
No Image Displayed

### ISSUE THREAD

**Issue by geauxtigers** [mewebstudio/captcha#50]
Installed package and pasted demo code in routes.php.  Only the image placeholder, text field, and button are displayed - no image and no errors when hitting the route (http://satest.dev/captcha-test).  Environment is Yosemite, Laravel 5.1, apache 2.4.1, php 5.6.11 with gd library.  Any suggestions?  Here is a screenshot of the page:

![image](https://cloud.githubusercontent.com/assets/8951542/9231215/99eb152e-40ec-11e5-9cd9-4df886b73fe0.png)

**Comment by mclxly** [comment]
same problem here~

**Comment by a-khajelou** [comment]
hi !
can you please do the following and create screen shot of the result :

1. right click on the not loaded image
2. inspect element [actually we want to inspect the image element]
3. in the inspector console you see the <img> tag , please open the img src in the new window
4. then screenshot the Exception window and send it here

i hope i can help you , thanks ! :)

**Comment by followtheart** [comment]
@mclxly example [here](https://github.com/followtheart/Laravel-5-Starter/blob/master/app/Http/routes.php#L46)

**Comment by mclxly** [comment]
@a-khajelou @followtheart Thank you!

I fixed the error with re-starting my web service. :)

**Comment by a-khajelou** [comment]
Oh , thanks god :)

**Comment by sharq88** [comment]
Had the same. If I open the image in a new tab: 
"Call to undefined function Intervention\Image\Gd\imagettfbbox"

Tried thousand things.. nothing worked.. then found that I used the native php boundled with mac, which wraps the GD. So I should change some config and recompile PHP. Bad way...

The easier route is to use brew php and replace in httpd.conf like:
#LoadModule php5_module libexec/apache2/libphp5.so
LoadModule php5_module /usr/local/Cellar/php55/5.5.30/libexec/apache2/libphp5.so

After this change, it worked immediately. :)
