### ISSUE TITLE
Captcha Font and Background Color

### ISSUE THREAD

**Issue by amatz5** [mewebstudio/captcha#51]
Can i change the font color and background color?

to make it simple background to transaparent
and font color to black.

**Comment by ageen** [comment]
I don't know how to set transparent in bgcolor, but you can set a  transparent bgImage

here in : config/captcha.php

return [
    //....
    'example'   => [
        'length'    => 6,
        'width'     => 160,
        'height'    => 46,
        'quality'   => 90,
        'lines'     => 6,
        'bgImage'   => 'background image uri',
        'bgColor'   => false,
        'fontColors'=> ['#2c3e50', '#c0392b', '#16a085', '#c0392b', '#8e44ad', '#303f9f', '#f57c00', '#795548'],
        'contrast'  => -5,
    ],
    // ...
];

then use this confg  captcha_img('example');

**Comment by amatz5** [comment]
thanks for the reply,

i change the bgImage with the URL of transparent image, but unfornately the catpcha image was broken.
