### ISSUE TITLE
How to refresh captcha image

### ISSUE THREAD

**Issue by tux-world** [mewebstudio/captcha#54]
i'm using this bundle in laravel 4, but i can not refresh captcha image by click on refresh icon

**Comment by followtheart** [comment]
Using jquery or zepto.js to bind click event .

**Comment by tux-world** [comment]
yes i know that, but i can not change that. i dont know how to change, please help me to use this useful package. thanks

**Comment by followtheart** [comment]
```js 
$('#captcha').click(function(){
    $('#captcha').attr('src','/captcha/default?'+Math.random());
    });
```

**Comment by tux-world** [comment]
Thanks. after click on captcha, thats set to hide and don't work correctly

**Comment by tux-world** [comment]
​Thanks sir. after click on CAPTCHA, image hide and dont refresh, thanks to
reply

**Comment by mewebstudio** [comment]
# jQuery AJAX example:

### routes.php
```php
Route::get('/get_captcha/{config?}', function (\Mews\Captcha\Captcha $captcha, $config = 'default') {
    return $captcha->src($config);
});
```

### view_file.blade.php
```php
<img src="{{ captcha_src() }}" alt="captcha" class="captcha-img" data-refresh-config="default">
```

### application.js
```javascript
$('img.captcha-img').on('click', function () {
    var captcha = $(this);
    var config = captcha.data('refresh-config');
    $.ajax({
        method: 'GET',
        url: '/get_captcha/' + config,
    }).done(function (response) {
        captcha.prop('src', response);
    });
});
```
Captcha image click to refresh.

**Comment by CN201** [comment]
I try to do that but it's not working sorry about my enlish

**Comment by KeepChen** [comment]
`<img src="{{captcha_src()}}" onclick="this.src='/captcha/default?'+Math.random()" id="captchaCode" alt="" class="captcha">`
`<a rel="nofollow" href="javascript:;" onclick="document.getElementById('captchaCode').src='captcha/default?'+Math.random()" class="reflash"></a>`
Hope to be helpful.

**Comment by CN201** [comment]
Thank you so much for reply  It works  ^ ^

**Comment by CN201** [comment]
Sorry to ask again, how to do multiple recaptcha on same page

**Comment by KeepChen** [comment]
@CN201 
See https://github.com/mewebstudio/captcha/issues/56

**Comment by CN201** [comment]
thank you KeepChen

**Comment by dontito94** [comment]
Thank you @keepchen

**Comment by abdulrojab** [comment]
@keepchen After searching in many discussions and tutorials, this method is great. Thank you, sir!

**Comment by kuyagep** [comment]
@keepchen Thank you!
