### ISSUE TITLE
Don't delete the session unless verification is passed

### ISSUE THREAD

**Issue by hardywen** [mewebstudio/captcha#55]
Sorry for my poor English.
In Captcha.php#line 415
```php
 $this->session->remove('captcha');
```
When I post a wrong captcha through AJAX,  I have to refresh the CAPTCHA.
Maybe it's better to delete the SESSION after  verification is passed rather then every time ?

**Comment by mewebstudio** [comment]
Described here :)
https://github.com/mewebstudio/captcha/issues/54#issuecomment-141483501
