### ISSUE TITLE
Multiple Captcha On One Page

### ISSUE THREAD

**Issue by pratikindia143** [mewebstudio/captcha#56]
I have one page which has multiple forms, I tried this but it is creating a problem.
I have already use this plugin on whole site and its working fine so i don't want to change the plugin.
Please help me out.

**Comment by mewebstudio** [comment]
I'm sorry :(
Multiple captcha not supported. Maybe it can be done in future versions.

**Comment by shailendra-fxbytes** [comment]
@mewebstudio Is this issue still exist?
