### ISSUE TITLE
This Bundle have and bug and dont work correctly

### ISSUE THREAD

**Issue by tux-world** [mewebstudio/captcha#57]
Hi all. i'm using this bundle on laravel 4.

in this bundle create session and check entered value have an bug, entered value and captcha always is correct but i get captcha is not correct error, please see this screen shot,

1) http://s6.uplod.ir/i/00684/dvvserezwfpe.png
2) http://s6.uplod.ir/i/00684/87j6ury2whsf.png

**Comment by mewebstudio** [comment]
To use https://github.com/mewebstudio/captcha/tree/master-l4

**Comment by Hesammousavi** [comment]
this error exist to laravel 5.2 ! why ?
