### ISSUE TITLE
Letters are visible partially 

### ISSUE THREAD

**Issue by salarmehr** [mewebstudio/captcha#62]
Thanks for this really useful package. 
Letters are are generally visible partially and some part are placed out of the canvas. I make reading hard. Also pleas consider adding an option to choose characters set (with this options)

**Comment by mani95lisa** [comment]
:+1:

**Comment by mewebstudio** [comment]
Maybe in the next version. Thanks :)

**Comment by salarmehr** [comment]
Any news for this issue? May in the next version ..........
