### ISSUE TITLE
Captcha validation always return invalid captcha

### ISSUE THREAD

**Issue by rupal-javiya** [mewebstudio/captcha#63]
As shown in documentation I have setup captcha package and set my /captcha-test

I am able to see captcha and textbox but whenever I submit form I always getting error  "validation.captcha" even if its not matter that captcha texts is right or wrong

am using laravel 5.0, please help, below is the form I setup in routes.php file

```php
Route::any('captcha-test', function()
{
    if (Request::getMethod() == 'POST')
    {
        $rules = ['captcha' => 'required|captcha'];
        $validator = Validator::make(Input::all(), $rules);
        if ($validator->fails())
        {
            echo '<p style="color: #ff0000;">Incorrect!</p>';
        }
        else
        {
            echo '<p style="color: #00ff30;">Matched :)</p>';
        }
    }

    $form = '<form method="post" action="captcha-test">';
    $form .= '<input type="hidden" name="_token" value="' . csrf_token() . '">';
    //$form .= '<p>' . captcha_img() . '</p>';
    $form .= '<img src="'. Captcha::src('inverse') .'" id="register-captcha-image">';
    $form .= '<p><input type="text" name="captcha"></p>';
    $form .= '<p><button type="submit" name="check">Check</button></p>';
    $form .= '</form>';
    return $form;
});

//For setting captcha route
Route::get('/captcha/{config?}', function (\Mews\Captcha\Captcha $captcha, $config = 'default') {
    return $captcha->src($config);
});
```

**Comment by bpratik11** [comment]
hello did you find any solution on this i'm facing same issue

**Comment by mewebstudio** [comment]
Use at least laravel 5.1.

**Comment by starkpratik** [comment]
hello i'm using latest 5.2

**Comment by mewebstudio** [comment]
It's ok.

Add `\Illuminate\Session\Middleware\StartSession::class` to `$middleware` in `Kernel.php`

The problem would be solved.
Happy coding.

**Comment by ragmon** [comment]
Hello,
have a simular problem on Laravel 5.2.

I'm using the helper function `captcha_src()` in my view form.
And still captcha validation always return invalid captcha.

But found solution here: [http://stackoverflow.com/a/34785340/2506123](url)
That's work fine for me.

Maybe you can fix it?

**Comment by ragmon** [comment]
Hello,
have a simular problem on Laravel 5.2.

I'm using the helper function captcha_src() in my view form.
And still captcha validation always return invalid captcha.

But found solution here: http://stackoverflow.com/a/34785340/2506123
That's work fine for me.

Maybe you can fix it?

**Comment by kaiphpdev** [comment]
> It's ok.
> 
> Add `\Illuminate\Session\Middleware\StartSession::class` to `$middleware` in `Kernel.php`
> 
> The problem would be solved.
> Happy coding.

Not Solve This problem I am Using 5.8
