### ISSUE TITLE
Issues with Laravel 5.2 - Session

### ISSUE THREAD

**Issue by archer96** [mewebstudio/captcha#64]
Laravel 5.2 removes important global middleware and introduces middleware groups.

This is great but also brought a "bug" to my app. All captchas were invalid since `\Illuminate\Session\Middleware\StartSession::class` wasn't used for the captcha image url.

Workarounds:

Add `\Illuminate\Session\Middleware\StartSession::class` to `$middleware` in `Kernel.php`

**or**

Change line 26 in CaptchaServiceProvider to:
```php
$this->app['router']->get('captcha/{config?}', '\Mews\Captcha\CaptchaController@getCaptcha')->middleware('web');
```

My question:

Is there any other way to fix this "issue" (if it is one).

Regards,
Andre

**Comment by mewebstudio** [comment]
Hi,
The first method is most appropriate. I'm using in this way.
Thanks.

**Comment by archer96** [comment]
Thank you :)
Could you add a note to `README.md`, please?

Regards,
Andre

**Comment by ayaka209** [comment]
+1 very useful, thank you!

**Comment by mewebstudio** [comment]
`README.md` add to note.
3e7f068def590c7987d1ef728003ea1ae309c7cb

**Comment by mousavian** [comment]
Since Laravel encourage developers to write their routes in the 'web' middleware ([The Default Routes File](https://laravel.com/docs/5.2/routing#basic-routing)), set another StartSession in default middleware will clear all session values that has been set by other classes.

In the same situation, second approach solved my problem.

**Comment by minibugdev** [comment]
Please note to `README.md` that if using `web` middleware on `route.php` must **NOT ADD** `\Illuminate\Session\Middleware\StartSession::class` to `protected $middleware`

Thank you,
Teeranai
