### ISSUE TITLE
No image display with BOM utf8

### ISSUE THREAD

**Issue by tienhsu** [mewebstudio/captcha#66]
Laravel 5.1 , xampp,  windows system, the image can't display.
At the end, found the php file in window is format utf8 with bom, hope this will be help with other people.

![99eb152e-40ec-11e5-9cd9-4df886b73fe0](https://cloud.githubusercontent.com/assets/8649627/12407858/ff92758a-be95-11e5-947d-5dff58c22e11.png)

**Comment by tannerjcox** [comment]
@tienhsu, what did you do to fix this?

**Comment by Zhenjas** [comment]
I have same problem, please tell how to fix this problem?

**Comment by stevejobsii** [comment]
@tienhsu how can you fix this problem thanks!

**Comment by stevejobsii** [comment]
@Zhenjas  can you fix this promblem right now?

**Comment by tienhsu** [comment]
@tannerjcox @stevejobsii @Zhenjas  found the php file in window is format utf8 with bom, just remove BOM format.

**Comment by tienhsu** [comment]
you can remove BOM with the following code:

public function CheckBomFile()
    {
        global $auto;
        set_time_limit(1000);
        if (isset($_GET['dir'])) { //Set the scan Directory
            $basedir = $_GET['dir'];
        } else {
            $basedir = './../app/';
        }
        $auto = 1;
        self::checkdir($basedir);
    }
    function checkdir($basedir)
    {
        if ($dh = opendir($basedir)) {
            while (($file = readdir($dh)) !== false) {
                if ($file != '.' && $file != '..') {
                    if (!is_dir($basedir . "/" . $file)) {
                        echo "filename: $basedir/$file " . self::checkBOM("$basedir/$file") . " <br>";
                    } else {
                        $dirname = $basedir . "/" . $file;
                        self::checkdir($dirname);
                    }
                }
            }
            closedir($dh);
        }
    }
    function checkBOM($filename)
    {
        global $auto;
        $contents   = file_get_contents($filename);
        $charset[1] = substr($contents, 0, 1);
        $charset[2] = substr($contents, 1, 1);
        $charset[3] = substr($contents, 2, 1);
        if (ord($charset[1]) == 239 && ord($charset[2]) == 187 && ord($charset[3]) == 191) {
            if ($auto == 1) {
                $rest = substr($contents, 3);
                self::rewrite($filename, $rest);
                return ("<font color=\"red\">BOM found, automatically removed.</font>");
            } else {
                return ("<font color=\"red\">BOM found.</font>");
            }
        } else
            return ("BOM Not Found.");
    }
    function rewrite($filename, $data)
    {
        $filenum = fopen($filename, "w");
        flock($filenum, LOCK_EX);
        fwrite($filenum, $data);
        fclose($filenum);
    }
