### ISSUE TITLE
laravel 5.2 without changes in kernel.php

### ISSUE THREAD

**Issue by william-smith** [mewebstudio/captcha#68]
// HTTP routing
        //route need in group of web middleware!!!
        $this->app['router']->group(['middleware' => 'web'], function () {
            $this->app['router']->get('captcha/{config?}', '\Mews\Captcha\CaptchaController@getCaptcha');
        });

**Comment by ionesculiviucristian** [comment]
Maybe someday...

**Comment by TiBianMod** [comment]
on laravel 5.2 all routes are group with the web middleware,
you can add on your routes.php this get route captcha/{config?} and you override the default from the package, and everything working.

`Route::get('captcha/{config?}', '\Mews\Captcha\CaptchaController@getCaptcha');`

**Comment by mewebstudio** [comment]
It solved the problem with the new version.
Please update packages.
