### ISSUE TITLE
session keeps regenerating on every request for 5.2

### ISSUE THREAD

**Issue by KailZhang** [mewebstudio/captcha#72]
Newbie to laravel.
While digging into the problem of session()->flash failure, I found the 
"for Laravel 5.2+ Add \Illuminate\Session\Middleware\StartSession::class to $middleware in Kernel.php"
is the culprit.
Session files keep regenerating after doing that.

**Comment by midi9x** [comment]
Same problem with me

**Comment by TiBianMod** [comment]
Remove the middleware from the kernel and add this to your routes.php

> `Route::get('captcha/{config?}', '\Mews\Captcha\CaptchaController@getCaptcha');`

if this is not working check your route:list and look for the route captcha/{config?} , need to have web middleware

if the middleware not exist on this URI captcha/{config?}' then simple add this

> `Route::get('captcha/{config?}', '\Mews\Captcha\CaptchaController@getCaptcha')->middleware('web');`

I hope this help you :)

**Comment by ycrao** [comment]
@TiBianMod try yours, but don't work for me

**Comment by TiBianMod** [comment]
you remove the middleware? if not remove the middleware

which version of laravel you have ?

run "php artisan route:list" and give me the results please

the results need to be similar with this with "web" on Middleware
```
+--------+----------+-----------------------------------------+----------------------------------+---------------------------------------------------------------+------------+
| Domain | Method   | URI                                     | Name                             | Action                                                        | Middleware |
+--------+----------+-----------------------------------------+----------------------------------+---------------------------------------------------------------+------------+
|        | GET|HEAD | captcha/{config?}                       | captcha                          | \Mews\Captcha\CaptchaController@getCaptcha                    | web        |
+--------+----------+-----------------------------------------+----------------------------------+---------------------------------------------------------------+------------+
```

**Comment by ycrao** [comment]
@TiBianMod 

Laravel 5.2
![20160421152742](https://cloud.githubusercontent.com/assets/3280204/14701059/c8e8ef30-07d5-11e6-874c-4eee312f6eba.jpg)

**Comment by TiBianMod** [comment]
follow this steps please.

go to app/Http/Kernel.php
make sure the \Illuminate\Session\Middleware\StartSession::class, is under the $middlewareGroups on "web" array, like this is by default end removed from the $middleware if is there

next

go to app/Http/routes.php and add this route:
> `Route::get('captcha/{config?}', '\Mews\Captcha\CaptchaController@getCaptcha');`

if something is wrong try this
> `Route::get('captcha/{config?}', '\Mews\Captcha\CaptchaController@getCaptcha')->middleware('web');`


### Important

> The \Illuminate\Session\Middleware\StartSession::class, Middleware need to be under the $middlewareGroups on the web array and not on $middleware array

**Comment by ycrao** [comment]
@TiBianMod 

I'm sure that this package route overwrite App's `captcha/{config?}` route.

![image](https://cloud.githubusercontent.com/assets/3280204/14730100/2cc9709c-0876-11e6-8bd0-ed4975130ce5.png)

![image](https://cloud.githubusercontent.com/assets/3280204/14730040/b007ac18-0875-11e6-88ce-e52fd2535af9.png)

**Comment by mewebstudio** [comment]
It solved the problem with the new version.
Please update packages.
