### ISSUE TITLE
Captcha verification error

### ISSUE THREAD

**Issue by petyots** [mewebstudio/captcha#74]
Hello, while i was at my developing server the captcha was working fine, now i deployed to production server and the check is always false. Thanks in advance.

**Comment by w3hacker** [comment]
When you visit http://domain/captcha/default?gYyVlEc5 your session doesn't change at all.

It's a bug of mewebstudio/captcha vs laravel 5.2. Waiting for someone to fix that.

**Comment by ionesculiviucristian** [comment]
You can try this fixed version:
https://github.com/ionesculiviucristian/captcha

**Comment by mewebstudio** [comment]
It solved the problem with the new version.
Please update packages.
