### ISSUE TITLE
Laravel 5.2: Captcha fails check even when it's correct

### ISSUE THREAD

**Issue by SoftwareGuy** [mewebstudio/captcha#76]
I'm using the Laravel 5.2 branch and for some reason, when you go to validate the captcha generated by `{{ captcha_img() }}` in a view, it will fail the validation and spit back "validation.captcha" which means that while there is no string that is available for use for captcha errors, the captcha failed anyway.

I am unable to debug this, but it seems to me that it can't cache the captcha to check. I believe I'm using the same library on another client's project, but I think that version is Laravel 5.0 and not 5.2.x.

Could someone please look into this? This is a bit of a pain because other than that, it's a solid captcha library. Thanks!

**Comment by w3hacker** [comment]
I changed vendor/mews/captcha/src/CaptchaServiceProvider.php file to

```
<?php

namespace Mews\Captcha;

use Illuminate\Support\ServiceProvider;

/**
 * Class CaptchaServiceProvider
 * @package Mews\Captcha
 */
class CaptchaServiceProvider extends ServiceProvider {

	/**
	 * Boot the service provider.
	 *
	 * @return null
	 */
	public function boot() {

		// Publish configuration files
		$this->publishes([
			__DIR__ . '/../config/captcha.php' => config_path('captcha.php'),
		], 'config');

		// HTTP routing
		if (strpos($this->app->version(), 'Lumen') !== false) {
			$this->app->get('captcha[/{config}]', 'Mews\Captcha\LumenCaptchaController@getCaptcha');
		} else {
			**$this->app['router']->get('captcha/{config?}', ['middleware' => 'web', 'uses' => '\Mews\Captcha\CaptchaController@getCaptcha']);**
		}

		// Validator extensions
		$this->app['validator']->extend('captcha', function ($attribute, $value, $parameters) {
			return captcha_check($value);
		});
	}

	/**
	 * Register the service provider.
	 *
	 * @return void
	 */
	public function register() {
		// Merge configs
		$this->mergeConfigFrom(
			__DIR__ . '/../config/captcha.php', 'captcha'
		);

		// Bind captcha
		$this->app->bind('captcha', function ($app) {
			return new Captcha(
				$app['Illuminate\Filesystem\Filesystem'],
				$app['Illuminate\Config\Repository'],
				$app['Intervention\Image\ImageManager'],
				$app['Illuminate\Session\Store'],
				$app['Illuminate\Hashing\BcryptHasher'],
				$app['Illuminate\Support\Str']
			);
		});
	}

}

```

It works. I don't know why

**Comment by ionesculiviucristian** [comment]
You can try this fixed version:
https://github.com/ionesculiviucristian/captcha

**Comment by SoftwareGuy** [comment]
@w3hacker your code modification has fixed the problem. Thank you very much!

Closing this now, hopefully the author will merge the edit into the code base to make it Laravel 5.2 ready.
