### ISSUE TITLE
Class captcha does not exist

### ISSUE THREAD

**Issue by 2111002778** [mewebstudio/captcha#79]
Hi
Sorry for my bad English.

I install mewebstudio captcha using composer "composer require mews/captcha", run bot  "composer update" and "composer install" .

Edit file "config/app.php" (I using laravel 5.1)

```
 'providers' => [
        // ...
        Mews\Captcha\CaptchaServiceProvider::class,
    ]

'aliases' => [
        // ...
        'Captcha' => Mews\Captcha\Facades\Captcha::class,
    ]
```

Run command line "php artisan vendor:publish" but it don't genarate file captcha.php in folder config (I must create it by hand).

When I put "{{ captcha_src() }}" in xxx.blade.php then it error 
"Class captcha does not exist (View: C:\wamp\www\lar\resources\views\xxx)"

Thanks

**Comment by mewebstudio** [comment]
Run the command and try again.
`composer dump`
