### ISSUE TITLE
The image cannot be displayed because it contains errors

### ISSUE THREAD

**Issue by dinajpuri** [mewebstudio/captcha#95]
Hello,
I've tested it with L 5.1 and 5.3. I'm not getting any captcha image. Tried switching imagick and gd in Intervention Image. But no luck.

Pls help.

Regards

**Comment by Kydz** [comment]
same problem, tried to dig it out but it`s really tricky, do you have any progress?

**Comment by dinajpuri** [comment]
Still no luck. I think this package is buggy

**Comment by pengxuxu** [comment]
@dinajpuri @Kydz you could add    **ob_clean();**   in getCaptcha method  of CaptchaController
![20161221133131](https://cloud.githubusercontent.com/assets/22192177/21378593/6e9d6b1a-c782-11e6-885e-5bf450caacab.png)

**Comment by vinodraut** [comment]
Thanks its working for me.

**Comment by ariabisri** [comment]
thats work.. thanks..
fyi: 
file location: \vendor\mews\captcha\src\CaptchaController.php
